name = "TestCI"
uuid = "48654f6e-0ac2-412f-88eb-bfb85e76823c"
authors = ["Yu-Chang YANG <yang.yc.allium@gmail.com>"]
version = "0.0.15"

[deps]

[compat]

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
